// Generated by https://quicktype.io
class Grupos {
  List<Grupo> items = [];

  Grupos();

  Grupos.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;

    for (var item in jsonList) {
      final grupo = new Grupo.fromJsonMap(item);
      items.add(grupo);
    }
  }
}

class Grupo {
  String cursos;

  Grupo({
    this.cursos,
  });

  Grupo.fromJsonMap(Map<String, dynamic> json) {
    cursos = json['CURSOS'];
  }
}
