// Generated by https://quicktype.io

import 'dart:collection';

class InformesTotales {
  //Lista con todos los registros
  List<Registro> items = [];
  //Listas de cadena para filtrar y no mostrar valores repetidos
  List<String> lista = [];
  //Lista para eliminar valores repetidos
  List<String> resultunico = [];
  InformesTotales();
  //Informes Lista
  InformesTotales.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;
    //Proceso todos los registros
    for (var item in jsonList) {
      final registro = new Registro.fromJsonMap(item);
      items.add(registro);
      var contador = 0;
      for (var vuelta in jsonList) {
        final linea = new Registro.fromJsonMap(vuelta);
        if (registro.alumno == linea.alumno) {
          contador++;
        }
      }
      //Añado todos los elementos los campos que necesitaremos mostrar
      lista.add((contador / 2).toString() +
          ' - Alumno:' +
          registro.alumno +
          '  - Curso:' +
          registro.curso);
    }

    //Eliminamos valores repetidos
    resultunico = LinkedHashSet<String>.from(lista).toList();
    //Ordenar de mas a menos salidas
    resultunico.sort((b, a) => a.compareTo(b));
  }
}

class Registro {
  String alumno;
  String curso;
  String diaHora;
  String accion;

  Registro({
    this.alumno,
    this.curso,
    this.diaHora,
    this.accion,
  });

  Registro.fromJsonMap(Map<String, dynamic> json) {
    alumno = json['ALUMNO'];
    curso = json['CURSO'];
    diaHora = json['Dia/Hora'];
    accion = json['Accion'];
  }
}
